{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "613f0157_e48a000c",
        "filename": "drivers/usb/dwc3/core-exynos.h",
        "patchSetId": 1
      },
      "lineNbr": 78,
      "author": {
        "id": 1557540
      },
      "writtenOn": "2022-04-12T16:57:45Z",
      "side": 0,
      "message": "These are just duplicates. Not sure why it didn\u0027t fail due to redefinitions :/",
      "range": {
        "startLine": 74,
        "startChar": 0,
        "endLine": 78,
        "endChar": 0
      },
      "revId": "0a5366d6dcb066f70f815ba057621ed195a9ddba",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}